import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import "./globals.css";

const redHatDisplay = Red_Hat_Display({
  variable: "--font-redhat-display",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "BrandAudit.ai — AI-Powered Brand Strategy Roadmap",
  description:
    "Submit your website or Instagram handle and receive a comprehensive AI-generated brand audit — visual identity, tone analysis, audience alignment, SEO health, and actionable upgrades delivered as a polished PDF.",
  keywords: [
    "brand audit",
    "brand strategy",
    "AI brand analysis",
    "brand identity",
    "digital marketing",
    "SEO audit",
    "Instagram audit",
  ],
  openGraph: {
    title: "BrandAudit.ai — Your Brand, Decoded by AI",
    description:
      "Get a comprehensive brand strategy roadmap generated by artificial intelligence. Submit your URL or Instagram handle.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${redHatDisplay.variable} dark`}
    >
      <body className="min-h-screen flex flex-col antialiased">
        {children}
      </body>
    </html>
  );
}
