import React from 'react';
import { Lead, ReportContent } from '@/lib/types/database';

interface BrandAuditReportProps {
  lead: Lead;
  reportContent: ReportContent;
}

export const BrandAuditReport: React.FC<BrandAuditReportProps> = ({ lead, reportContent }) => {
  const { scores, executive_summary, actionable_upgrades } = reportContent;

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-green-600';
    if (score >= 60) return 'text-yellow-600';
    return 'text-red-600';
  };

  return (
    <div className="bg-white min-h-[297mm] w-[210mm] mx-auto p-12 text-slate-900 font-sans">
      {/* Header */}
      <header className="border-b-4 border-slate-900 pb-6 mb-10">
        <h1 className="text-4xl font-extrabold tracking-tight uppercase text-slate-900">
          Brand Audit Report
        </h1>
        <p className="text-lg text-slate-500 mt-2 font-medium">
          Prepared for <span className="text-slate-900 font-bold">{lead.company_name || lead.name}</span>
        </p>
        <p className="text-sm text-slate-400 mt-1">
          Target: {lead.identifier} | Industry: {lead.industry || 'N/A'}
        </p>
      </header>

      {/* Executive Summary */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-4 uppercase tracking-wider text-slate-800">Executive Summary</h2>
        <div className="prose prose-slate max-w-none text-lg leading-relaxed whitespace-pre-wrap">
          {executive_summary}
        </div>
      </section>

      {/* Scores */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6 uppercase tracking-wider text-slate-800">Brand Performance</h2>
        <div className="grid grid-cols-3 gap-6">
          <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 text-center">
            <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wide">Visual Consistency</h3>
            <p className={`text-5xl font-black mt-3 ${getScoreColor(scores.visual_consistency)}`}>
              {scores.visual_consistency}
            </p>
          </div>
          <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 text-center">
            <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wide">Messaging Clarity</h3>
            <p className={`text-5xl font-black mt-3 ${getScoreColor(scores.messaging_clarity)}`}>
              {scores.messaging_clarity}
            </p>
          </div>
          <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 text-center">
            <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wide">Audience Alignment</h3>
            <p className={`text-5xl font-black mt-3 ${getScoreColor(scores.audience_alignment)}`}>
              {scores.audience_alignment}
            </p>
          </div>
        </div>
      </section>

      {/* Actionable Upgrades */}
      <section>
        <h2 className="text-2xl font-bold mb-6 uppercase tracking-wider text-slate-800">Actionable Upgrades</h2>
        <div className="space-y-6">
          {actionable_upgrades.map((upgrade, idx) => (
            <div key={idx} className="bg-white border-l-4 border-slate-900 shadow-sm p-6 rounded-r-lg">
              <span className="inline-block bg-slate-900 text-white text-xs font-bold uppercase tracking-wider py-1 px-3 rounded-full mb-3">
                {upgrade.category}
              </span>
              <h3 className="text-xl font-bold text-slate-800 mb-2">Issue: {upgrade.issue}</h3>
              <p className="text-slate-600 font-medium">
                <span className="text-slate-900 font-bold">Fix: </span>
                {upgrade.fix}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="mt-16 pt-8 border-t border-slate-200 text-center text-slate-400 text-sm">
        <p>Generated by Megamind Brand Auditing Platform &copy; {new Date().getFullYear()}</p>
      </footer>
    </div>
  );
};
